export interface ScanResult {
  url: string;
  timestamp: string;
  visitedUrls: string[];
  forms: { action: string; method: string; inputs: string[] }[];
  missingHeaders: { header: string; severity: "high" | "medium" | "low"; description: string }[];
  xssFindings: { url: string; parameter: string; payload: string }[];
}

const MOCK_DELAY = 4000;

export async function runMockScan(targetUrl: string): Promise<ScanResult> {
  await new Promise((r) => setTimeout(r, MOCK_DELAY));

  const base = targetUrl.replace(/\/$/, "");

  return {
    url: targetUrl,
    timestamp: new Date().toISOString(),
    visitedUrls: [
      base,
      `${base}/about`,
      `${base}/login`,
      `${base}/contact`,
      `${base}/dashboard`,
      `${base}/api/v1/users`,
    ],
    forms: [
      { action: `${base}/login`, method: "POST", inputs: ["username", "password"] },
      { action: `${base}/contact`, method: "POST", inputs: ["name", "email", "message"] },
    ],
    missingHeaders: [
      { header: "Strict-Transport-Security", severity: "high", description: "HSTS not set. The site does not enforce HTTPS connections." },
      { header: "Content-Security-Policy", severity: "high", description: "No CSP defined. The site is vulnerable to content injection attacks." },
      { header: "X-Frame-Options", severity: "medium", description: "Missing clickjacking protection header." },
      { header: "X-Content-Type-Options", severity: "low", description: "Browser MIME-type sniffing not disabled." },
    ],
    xssFindings: [
      { url: `${base}/search?q=`, parameter: "q", payload: '<script>alert("xss")</script>' },
      { url: `${base}/contact?ref=`, parameter: "ref", payload: '"><img src=x onerror=alert(1)>' },
    ],
  };
}

export function generateHtmlReport(result: ScanResult): string {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>LunaScan Report — ${result.url}</title>
<style>
body{font-family:system-ui,sans-serif;background:#1a1c23;color:#e2e2e8;padding:40px;max-width:900px;margin:auto}
h1{color:#c084fc}h2{color:#a78bfa;margin-top:32px;border-bottom:1px solid #333;padding-bottom:8px}
table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #2a2d35}
th{color:#c084fc;font-size:13px;text-transform:uppercase;letter-spacing:0.5px}
.badge{display:inline-block;padding:2px 10px;border-radius:99px;font-size:12px;font-weight:600}
.high{background:#7f1d1d;color:#fca5a5}.medium{background:#78350f;color:#fcd34d}.low{background:#1e3a5f;color:#93c5fd}
code{background:#23252e;padding:2px 6px;border-radius:4px;font-size:13px}
</style></head><body>
<h1>🌙 LunaScan Report</h1>
<p><strong>Target:</strong> ${result.url}<br><strong>Scanned:</strong> ${new Date(result.timestamp).toLocaleString()}</p>

<h2>Visited URLs (${result.visitedUrls.length})</h2>
<ul>${result.visitedUrls.map((u) => `<li>${u}</li>`).join("")}</ul>

<h2>Extracted Forms (${result.forms.length})</h2>
<table><tr><th>Action</th><th>Method</th><th>Inputs</th></tr>
${result.forms.map((f) => `<tr><td>${f.action}</td><td>${f.method}</td><td>${f.inputs.join(", ")}</td></tr>`).join("")}</table>

<h2>Missing Security Headers (${result.missingHeaders.length})</h2>
<table><tr><th>Header</th><th>Severity</th><th>Description</th></tr>
${result.missingHeaders.map((h) => `<tr><td><code>${h.header}</code></td><td><span class="badge ${h.severity}">${h.severity}</span></td><td>${h.description}</td></tr>`).join("")}</table>

<h2>Reflected XSS Findings (${result.xssFindings.length})</h2>
<table><tr><th>URL</th><th>Parameter</th><th>Payload</th></tr>
${result.xssFindings.map((x) => `<tr><td>${x.url}</td><td><code>${x.parameter}</code></td><td><code>${x.payload.replace(/</g, "&lt;")}</code></td></tr>`).join("")}</table>

<p style="margin-top:40px;color:#666;font-size:12px">Generated by LunaScan</p>
</body></html>`;
}
